// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `erp.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.lpmas.erp.component;

public final class ErpServicePrxHolder
{
    public
    ErpServicePrxHolder()
    {
    }

    public
    ErpServicePrxHolder(ErpServicePrx value)
    {
        this.value = value;
    }

    public ErpServicePrx value;
}
